<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/']], [], [], []],
    'landing_page' => [[], ['_controller' => 'App\\Controller\\LandingPageController::index'], [], [['text', '/landing']], [], [], []],
    'App\Controller\DashboardController::index' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\LandingPageController::index' => [[], ['_controller' => 'App\\Controller\\LandingPageController::index'], [], [['text', '/landing']], [], [], []],
];
